### ISSUE TITLE
catch_config_error() missing 1 required positional argument: 'app'

### ISSUE THREAD

**Issue by ansionfor** [emilwallner/Screenshot-to-code-in-Keras#4]
E:\software\python3\demo\Screenshot-to-code-in-Keras-master\local>jupyter notebo
ok
Traceback (most recent call last):
  File "e:\software\python3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\software\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\software\python3\Scripts\jupyter-notebook.EXE\__main__.py", line 5, i
n <module>
  File "e:\software\python3\lib\site-packages\notebook\__init__.py", line 25, in
 <module>
    from .nbextensions import install_nbextension
  File "e:\software\python3\lib\site-packages\notebook\nbextensions.py", line 32
, in <module>
    from traitlets.config.manager import BaseJSONConfigManager
  File "e:\software\python3\lib\site-packages\traitlets\config\__init__.py", lin
e 6, in <module>
    from .application import *
  File "e:\software\python3\lib\site-packages\traitlets\config\application.py",
line 120, in <module>
    class Application(SingletonConfigurable):
  File "e:\software\python3\lib\site-packages\traitlets\config\application.py",
line 291, in Application
    def initialize(self, argv=None):
TypeError: catch_config_error() missing 1 required positional argument: 'app'

Why I get this?

**Comment by ansionfor** [comment]
pip  install decorator==4.1.2

I found this：
https://stackoverflow.com/questions/48248521/catch-config-error-while-trying-to-run-ipython3
